services:
  php:
    container_name: "fuel-php"
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: local
    volumes:
      - ./src:/var/www
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=phper
      - DB_PASSWORD=secret
    depends_on:
      - db
  web:
    container_name: "fuel-web"
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      target: local
    ports:
      - "8080:80"
    volumes:
      - ./src/public:/var/www/public
    depends_on:
      - php
  db:
    container_name: "fuel-db"
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=phper
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
  mailhog:
    container_name: "fuel-mailhog"
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  db-store: